### ISSUE TITLE
一直报错 Could not invoke JPushModule.initPush

### ISSUE THREAD

**Issue by z330789559** [jpush/jpush-react-native#154]
Exception in native call
                                                                  java.lang.RuntimeException: Could not invoke JPushModule.initPush
                                                                      at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:333)
                                                                      at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
                                                                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                      at android.os.Handler.handleCallback(Handler.java:725)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                      at android.os.Looper.loop(Looper.java:137)
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                      at java.lang.Thread.run(Thread.java:856)
                                                                   Caused by: java.lang.reflect.InvocationTargetException
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:511)
                                                                      at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
                                                                      at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158) 
                                                                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                      at android.os.Handler.handleCallback(Handler.java:725) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                      at android.os.Looper.loop(Looper.java:137) 
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                                      at java.lang.Thread.run(Thread.java:856) 
                                                                   Caused by: java.lang.ExceptionInInitializerError
                                                                      at cn.jpush.reactnativejpush.JPushModule.initPush(JPushModule.java:69)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                      at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319) 
                                                                      at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158) 
                                                                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                      at android.os.Handler.handleCallback(Handler.java:725) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                      at android.os.Looper.loop(Looper.java:137) 
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                                      at java.lang.Thread.run(Thread.java:856) 
                                                                   Caused by: java.lang.ExceptionInInitializerError
                                                                      at cn.jpush.android.api.JPushInterface.<clinit>(Unknown Source)
                                                                      at cn.jpush.reactnativejpush.JPushModule.initPush(JPushModule.java:69) 
                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                      at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319) 
                                                                      at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158) 
                                                                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                      at android.os.Handler.handleCallback(Handler.java:725) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                      at android.os.Looper.loop(Looper.java:137) 
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                                      at java.lang.Thread.run(Thread.java:856) 
                                                                   Caused by: java.lang.NoClassDefFoundError: cn.jiguang.api.SdkType
                                                                      at cn.jpush.android.d.<clinit>(Unknown Source)
                                                                      at cn.jpush.android.api.JPushInterface.<clinit>(Unknown Source) 
                                                                      at cn.jpush.reactnativejpush.JPushModule.initPush(JPushModule.java:69) 
                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                      at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319) 
                                                                      at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158) 
                                                                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                      at android.os.Handler.handleCallback(Handler.java:725) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                      at android.os.Looper.loop(Looper.java:137) 
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                                      at java.lang.Thread.run(Thread.java:856)

**Comment by lilfei** [comment]
so am I

**Comment by KenChoi1992** [comment]
@z330789559 @lilfei https://github.com/jpush/jpush-react-native/issues/152 看下这个 issue，在 onCreate 中调用一下 initPush()

**Comment by lilfei** [comment]
@KenChoi1992 @z330789559  把jcore-react-native 手动link一下就好了。

**Comment by KenChoi1992** [comment]
@lilfei 因为 jcore 从 jpush 分离出来，所以才导致这个问题吧，稍后更新一下文档。

**Comment by lilfei** [comment]
@KenChoi1992 jcore的link不好用。，用react-native link没加上，手动加的。不知是我一个问题还是都有

**Comment by cyzaoj** [comment]
+1
