### ISSUE TITLE
Didn't find class mainActivity on path: DexPathList

### ISSUE THREAD

**Issue by pampang** [jpush/jpush-react-native#174]
app在后台，点击推送，无法调起mainActivity。

```
03-17 10:50:07.383 30261-30261/com.shefenqi.mall D/JPushModule: 用户点击打开了通知
03-17 10:50:07.386 30261-30261/com.shefenqi.mall W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
03-17 10:50:07.386 30261-30261/com.shefenqi.mall W/System.err:     at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:308)
03-17 10:50:07.386 30261-30261/com.shefenqi.mall W/System.err:     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2788)
03-17 10:50:07.386 30261-30261/com.shefenqi.mall W/System.err:     at android.app.ActivityThread.access$1800(ActivityThread.java:168)
03-17 10:50:07.386 30261-30261/com.shefenqi.mall W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1456)
03-17 10:50:07.386 30261-30261/com.shefenqi.mall W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-17 10:50:07.386 30261-30261/com.shefenqi.mall W/System.err:     at android.os.Looper.loop(Looper.java:150)
03-17 10:50:07.386 30261-30261/com.shefenqi.mall W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5665)
03-17 10:50:07.387 30261-30261/com.shefenqi.mall W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-17 10:50:07.387 30261-30261/com.shefenqi.mall W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
03-17 10:50:07.387 30261-30261/com.shefenqi.mall W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
03-17 10:50:07.387 30261-30261/com.shefenqi.mall I/JPushModule: Try to start application
03-17 10:50:07.387 30261-30261/com.shefenqi.mall W/System.err: java.lang.ClassNotFoundException: Didn't find class "com.shefenqi.mall.MainActivity" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
03-17 10:50:07.387 30261-30261/com.shefenqi.mall W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:     at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:322)
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2788)
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:     at android.app.ActivityThread.access$1800(ActivityThread.java:168)
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1456)
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:     at android.os.Looper.loop(Looper.java:150)
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5665)
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:     Suppressed: java.lang.ClassNotFoundException: com.shefenqi.mall.MainActivity
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:     at java.lang.Class.classForName(Native Method)
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:         ... 11 more
03-17 10:50:07.388 30261-30261/com.shefenqi.mall W/System.err:     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

部分AndroidManifest.xml

```
<application
        android:name=".MainApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:theme="@style/AppTheme">
        <activity
            android:name=".MainActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:exported="true"
            android:label="@string/app_name"
            android:launchMode="singleTask"
            android:screenOrientation="portrait">
```

**Comment by pampang** [comment]
看样子是https://github.com/jpush/jpush-react-native/blob/master/android/src/main/java/cn/jpush/reactnativejpush/JPushModule.java#L308中的mContext.getClass()出问题了？空指针？

**Comment by KenChoi1992** [comment]
@pampang 参考一下这里的代码：https://github.com/jpush/jpush-react-native/blob/dev/android/src/main/java/cn/jpush/reactnativejpush/JPushModule.java#L321 看看能否解决你的问题。

**Comment by pampang** [comment]
下面那个错误就是对应的位置报的。。。

**Comment by pampang** [comment]
。。。。。突然发现是没有执行在js端`JPushModule.initPush()`，导致mModule.mContext为空。。。
这个逻辑不合理啊。。。。。。。。。。。。。。。
mContext就是getCurrentActivity()而已呀。。。

**Comment by KenChoi1992** [comment]
@pampang 参考一下新版本的 demo，init 动作放在 Native 里的 MainActivity 了。

**Comment by KenChoi1992** [comment]
@pampang 没有其他问题就关闭了。
