### ISSUE TITLE
魅族手机 getRegistrationID 无效

### ISSUE THREAD

**Issue by xwartz** [jpush/jpush-react-native#196]
版本信息：
```
"react-native": "0.37.0",
"jpush-react-native": "^1.3.5",
```

错误信息：

```
#0. Crashed: mqt_native_modules: 0 0 0x0000000000000000
       at cn.jpush.android.api.JPushInterface.a(Unknown Source)
       at cn.jpush.android.api.JPushInterface.getRegistrationID(Unknown Source)
       at cn.jpush.reactnativejpush.JPushModule.getRegistrationID(JPushModule.java:219)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:193)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:848)
```

看错误信息，应该是 `getCurrentActivity` 拿到了 NULL，麻烦帮看下。

**Comment by KenChoi1992** [comment]
你在 getRegistrationID 之前有没有 先调用 init ？

**Comment by xwartz** [comment]
调用了 initPush

**Comment by xwartz** [comment]
目前发现只有少部分手机出现这种情况，魅族比较多

**Comment by KenChoi1992** [comment]
@xwartz 在你的根 Component 下拿的吗？

**Comment by xwartz** [comment]
@KenChoi1992   就是在根 component 调的，拿不到，不过目前主要是没有可重现的手机，不好 debug 😩  。

**Comment by xwartz** [comment]
@KenChoi1992 
我看 RN issue 上有 [getCurrentActivity null 的情况](https://github.com/facebook/react-native/issues/9310)，但已经修复

**Comment by KenChoi1992** [comment]
你升级一下版本试试？

**Comment by xwartz** [comment]
@KenChoi1992   暂时没时间升级 RN，太多 breaking changes 了，我暂时先捕获这个错误，不让 crash
 试试吧。

**Comment by KenChoi1992** [comment]
@xwartz 没什么问题就关闭这个 issue 了。
