### ISSUE TITLE
无法获取到registrationid 安卓

### ISSUE THREAD

**Issue by Woodswu** [jpush/jpush-react-native#204]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
 at android.widget.Toast.<init>(Toast.java:102)
 at android.widget.Toast.makeText(Toast.java:266)
 at cn.jpush.reactnativejpush.Logger.toast(Logger.java:26)
 at cn.jpush.reactnativejpush.JPushModule.initPush(JPushModule.java:74)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
 at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
 at android.os.Handler.handleCallback(Handler.java:739)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
 at android.os.Looper.loop(Looper.java:148)
 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
 at java.lang.Thread.run(Thread.java:818)

componentDidMount(){
   JPushModule.initPush();
    JPushModule.getInfo((map)=>{
           console.log(map);
       })
     JPushModule.getRegistrationID((registrationId)=>{
         console.log("Device register succeed, registrationId " + registrationId);
         _this.setState({registrationid:registrationId});

     });
}
能获取信息但是无法获取ID，用init也会报错

    "jcore-react-native": "^1.1.0",
    "jpush-react-native": "^1.6.0",

**Comment by KenChoi1992** [comment]
@Woodswu 建议在 `MainActivity` 中进行初始化：
```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        JPushInterface.init(this);
    }
```

**Comment by Woodswu** [comment]
java.lang.IllegalArgumentException: NULL context
 at cn.jpush.android.api.JPushInterface.a(Unknown Source)
 at cn.jpush.android.api.JPushInterface.getRegistrationID(Unknown Source)
 at cn.jpush.reactnativejpush.JPushModule.getRegistrationID(JPushModule.java:224)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
 at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
 at android.os.Handler.handleCallback(Handler.java:739)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
 at android.os.Looper.loop(Looper.java:148)
 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
 at java.lang.Thread.run(Thread.java:818)

嗯，我采用了你说的额此方法，但是运行起来会出现这个错误

**Comment by Woodswu** [comment]
@KenChoi1992 
上面的错误我吧 getRegistrationID 更换了这个方法 addGetRegistrationIdListener

虽然没有错误出现，但是仍然无法接收到ID 没有任何返回

**Comment by KenChoi1992** [comment]
@Woodswu 估计 `mContext = getCurrentActivity();` 这句拿的是空指针了，你是在 MainActivity 对应的 component 拿的吗？

**Comment by rocwangv** [comment]
+1,
请问这个问题现在有进展吗？谢谢

**Comment by KenChoi1992** [comment]
@rocwangv 更新了 JPush SDK，你们都是在 MainActivity 初始化的嘛？

> MainActivity.java

```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        JPushInterface.init(this);
    }
```

**Comment by rocwangv** [comment]
@KenChoi1992 我上午加了你这句在MainActivity，然后打了一个apk之后，再回来调试debug版本的就没问题了。。

**Comment by KenChoi1992** [comment]
嗯，那就是这块你在拿 registrationId 的时候没有初始化导致。@Woodswu 不知道你是不是这样。

**Comment by KenChoi1992** [comment]
没什么问题就关掉这个 issue 了。
