### ISSUE TITLE
1.6.0 error

### ISSUE THREAD

**Issue by lzctbyong** [jpush/jpush-react-native#208]
04-24 12:36:47.238 1722-1722/com.gzwx.wxjstaffapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.gzwx.wxjstaffapp, PID: 1722
                                                                    java.lang.NoClassDefFoundError: cn.jpush.android.a.b
                                                                        at cn.jpush.android.api.JPushInterface.<clinit>(Unknown Source)
                                                                        at com.gzwx.wxjstaffapp.MainActivity.onCreate(MainActivity.java:26)

**Comment by lzctbyong** [comment]
java.lang.NoClassDefFoundError: cn.jpush.android.a.b
