### ISSUE TITLE
 [Android] Tried to access a JS module before the React instance was fully set up

### ISSUE THREAD

**Issue by xuetongiqn** [jpush/jpush-react-native#217]
线上友盟统计发现，多个用户出现如下报错：

> java.lang.RuntimeException: Unable to start receiver cn.jpush.reactnativejpush.JPushModule$JPushReceiver: java.lang.RuntimeException: Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module.
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2862)
	at android.app.ActivityThread.access$1600(ActivityThread.java:183)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5667)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
Caused by: java.lang.RuntimeException: Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module.
	at com.facebook.react.bridge.ReactContext.getJSModule(ReactContext.java:109)
	at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:263)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2855)
	... 9 more
java.lang.RuntimeException: Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module.
	at com.facebook.react.bridge.ReactContext.getJSModule(ReactContext.java:109)
	at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:263)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2855)
	at android.app.ActivityThread.access$1600(ActivityThread.java:183)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5667)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

看错误报告，应该是在reactnative加载完成之前，调用了getJSModule

**Comment by KenChoi1992** [comment]
@xuetongiqn 感谢提供反馈，这块是在应用未启动收到通知后报错的吗？

**Comment by KenChoi1992** [comment]
@xuetongiqn 发布了新版本，修复了这个问题。

**Comment by xuetongiqn** [comment]
👍真高效！

**Comment by jimitpatel** [comment]
It would be good if written in english. Thanks in advance
