### ISSUE TITLE
com.android.dex.DexException: Multiple dex files define Lcn/jpush/a/a;

### ISSUE THREAD

**Issue by kala888** [jpush/jpush-react-native#259]
"react-native": "^0.45.1",

开始是"jcore-react-native": "^1.1.3",
    "jpush-react-native": "1.6.6",
后来换成demo里的
    "jcore-react-native": "^1.1.0",
    "jpush-react-native": "^1.6.0",

同样的b报错信息
```
Running dex in-process requires build tools 23.0.2.
For faster builds update this project to use the latest build tools.
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcn/jpush/a/a;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcn/jpush/a/a;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
```

执行的命令
 ```
rm -rf android/build
rm -rf android/app/build
rm -rf node_modules &&  npm i && react-native link && react-native run-android
```

**Comment by forrest23** [comment]
I use gradlew assembleRelease  and show the same error 
    "jcore-react-native": "^1.1.3",
    "jpush-react-native": "^1.6.6",  
    "react-native": "^0.44.0",

**Comment by forrest23** [comment]
I also use react-native-jmessage

**Comment by KenChoi1992** [comment]
@forrest23 jmessage and jpush are both depend on jcore, so you need to keep just one jcore, and do remember, jcore should match both of them.

**Comment by KenChoi1992** [comment]
@kala888 如果你没有使用 jmessage，那么只要删掉 build 文件夹，重新编译就没问题了，如果用了，那么需要删掉一个 jcore，只保留一个 jcore，并且 jcore 要同时匹配 jmessage 和 jpush。

**Comment by zhubaobao** [comment]
@kala888 这个问题解决了吗？我也遇到了

**Comment by huangxubo23** [comment]
包依赖：
```
  "jcore-react-native": "^1.1.3",
  "jpush-react-native": "^1.6.6",
  "react-native": "0.45.1"
```

同样报以下的错误：
```
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcn/jpush/a/a;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcn/jpush/a/a;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
    
:app:transformClassesWithDexForDebug FAILED
```

```
* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
```

请问有人解决了吗？

**Comment by kala888** [comment]
@huangxubo23 
不要用最新的包，把依赖包改为可以用的
  "jcore-react-native": "^1.1.0",
    "jpush-react-native": "1.6.0",

**Comment by KenChoi1992** [comment]
@kala888  @huangxubo23 @forrest23 新版本应该解决这个问题了。

**Comment by huanxsd** [comment]
同样出现了这个问题
