### ISSUE TITLE
iOS 是正常的，Android这边点击推送消息会报android.content.ActivityNotFoundException

### ISSUE THREAD

**Issue by ribuluo000** [jpush/jpush-react-native#324]
`08-16 14:31:49.270 3735-3735/com.yoopard.bolt W/System.err:     at dalvik.system.NativeStart.main(Native Method)
08-16 14:31:52.905 3735-3735/com.yoopard.bolt W/System.err: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.yoopard.bolt/com.yoopard.bolt.MainActivity}; have you declared this activity in your AndroidManifest.xml?
08-16 14:31:52.905 3735-3735/com.yoopard.bolt W/System.err:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1639)
08-16 14:31:52.915 3735-3735/com.yoopard.bolt W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1435)
08-16 14:31:52.915 3735-3735/com.yoopard.bolt W/System.err:     at android.app.ContextImpl.startActivity(ContextImpl.java:1115)
08-16 14:31:52.915 3735-3735/com.yoopard.bolt W/System.err:     at android.app.ContextImpl.startActivity(ContextImpl.java:1086)
08-16 14:31:52.915 3735-3735/com.yoopard.bolt W/System.err:     at android.content.ContextWrapper.startActivity(ContextWrapper.java:311)
08-16 14:31:52.915 3735-3735/com.yoopard.bolt W/System.err:     at android.content.ContextWrapper.startActivity(ContextWrapper.java:311)
08-16 14:31:52.915 3735-3735/com.yoopard.bolt W/System.err:     at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:470)
08-16 14:31:52.915 3735-3735/com.yoopard.bolt W/System.err:     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2533)
08-16 14:31:52.915 3735-3735/com.yoopard.bolt W/System.err:     at android.app.ActivityThread.access$2000(ActivityThread.java:139)
08-16 14:31:52.915 3735-3735/com.yoopard.bolt W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1337)
08-16 14:31:52.915 3735-3735/com.yoopard.bolt W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
08-16 14:31:52.915 3735-3735/com.yoopard.bolt W/System.err:     at android.os.Looper.loop(Looper.java:136)
08-16 14:31:52.915 3735-3735/com.yoopard.bolt W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5314)
08-16 14:31:52.915 3735-3735/com.yoopard.bolt W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
08-16 14:31:52.915 3735-3735/com.yoopard.bolt W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
08-16 14:31:52.915 3735-3735/com.yoopard.bolt W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
08-16 14:31:52.915 3735-3735/com.yoopard.bolt W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
08-16 14:31:52.915 3735-3735/com.yoopard.bolt W/System.err:     at dalvik.system.NativeStart.main(Native Method)
`

之前的版本是好的，当前的版本是不好的。
当前版本：
    "jcore-react-native": "1.1.8",
    "jpush-react-native": "2.0.4",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.2",

该怎么解决呢？
<img width="615" alt="qq20170816-145505 2x" src="https://user-images.githubusercontent.com/9551756/29350890-f22ce912-8292-11e7-8d48-41b2d6e6b120.png">
<img width="545" alt="qq20170816-150729 2x" src="https://user-images.githubusercontent.com/9551756/29351292-bea9baaa-8294-11e7-80e1-be1c6f146d3e.png">
<img width="343" alt="qq20170816-150756 2x" src="https://user-images.githubusercontent.com/9551756/29351316-d19d3f2e-8294-11e7-92a4-a0f82a085ecd.png">

**Comment by ribuluo000** [comment]
我已经解决了这个问题。。。
通过将JPushModule.java 文件中
<img width="869" alt="qq20170816-165558 2x" src="https://user-images.githubusercontent.com/9551756/29355722-ae3fe094-82a4-11e7-997e-a034d0d9714e.png">
改为：
<img width="847" alt="qq20170816-165649 2x" src="https://user-images.githubusercontent.com/9551756/29355740-bb057c6c-82a4-11e7-94c8-ad014563da8d.png">
