### ISSUE TITLE
Dex: Error converting bytecode to dex: Cause: com.android.dex.DexException: Multiple dex files define Lcn/jiguang/a/a/a/a;

### ISSUE THREAD

**Issue by bobo870403** [jpush/jpush-react-native#342]
android环境下报错，ios没问题，关键是突然就不行了，前面还一直在用的，降级到1.1.6版本也不行，按照前面一些前辈解决这个问题的思路试了下，都失败了。
For faster builds update this project to use the latest build tools.
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcn/jiguang/a/a/a/a;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcn/jiguang/a/a/a/a;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

我的版本    "jcore-react-native": "^1.1.8",
                   "jpush-react-native": "^2.0.6",

**Comment by KenChoi1992** [comment]
@bobo870403 删掉 jpush-react-native 下的 build 文件夹，重新 build。

**Comment by bobo870403** [comment]
@KenChoi1992 试过了，我吧jpush-react-native下的build删了，把我自己项目下的build也清空了，还是同样的错误

**Comment by bobo870403** [comment]
我已经解决了，把所以jcore重新install了下，删除了所有的build下的文件，重新编译通过了

**Comment by KenChoi1992** [comment]
@bobo870403 ok, 那我关掉了
