### ISSUE TITLE
"npm run configureJPush myselfKey app"  报错

### ISSUE THREAD

**Issue by jiexishede** [jpush/jpush-react-native#345]
"npm run configureJPush myselfKey app"  报错　
　自己执行这个以后包错了，报错信息。。　

`fs.js:953
  binding.stat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, stat '/Users/yianwork/APP/patient/ios/build/Build/Products/Debug-iphonesimulator/SDWebImage iOS static.framework/SDWebImage iOS static'
    at Object.fs.statSync (fs.js:953:11)
    at eachFileSync (/Users/yianwork/APP/patient/node_modules/jpush-react-native/JPushConfiguration.js:208:17)
    at /Users/yianwork/APP/patient/node_modules/jpush-react-native/JPushConfiguration.js:216:4
    at Array.forEach (native)
    at eachFileSync (/Users/yianwork/APP/patient/node_modules/jpush-react-native/JPushConfiguration.js:215:9)
    at /Users/yianwork/APP/patient/node_modules/jpush-react-native/JPushConfiguration.js:216:4
    at Array.forEach (native)
    at eachFileSync (/Users/yianwork/APP/patient/node_modules/jpush-react-native/JPushConfiguration.js:215:9)
    at /Users/yianwork/APP/patient/node_modules/jpush-react-native/JPushConfiguration.js:216:4
    at Array.forEach (native)`

**Comment by huangminlinux** [comment]
是在工程主目录执行的命令吗，提示是路径没有找到，  截图看看你的工程结构。

**Comment by jiexishede** [comment]
我在在安装　两个依赖库的　路径上执行的这两个　命令。。
![default](https://user-images.githubusercontent.com/9484734/30268049-091426b6-9717-11e7-8d33-51934627adbd.png)

**Comment by jiexishede** [comment]
怎么添加这个文件，　没有啊。

**Comment by huangminlinux** [comment]
你要在 RN 的主工程目录中执行这个命令。

**Comment by jiexishede** [comment]
什么叫　ＲＮ的主工程目录。　我是在　平时安卓　依赖库的路径下执行的。　就是在　`npm install jcore-react-native --save` 　这个命令执行下的目录跑的这个脚本。

**Comment by jiexishede** [comment]
下班了吗、？

**Comment by jiexishede** [comment]
删了这个文件，　继续搞可以　收到通知了。
