### ISSUE TITLE
npm run configureJPush error

### ISSUE THREAD

**Issue by xwartz** [jpush/jpush-react-native#378]
## 你的运行环境

* 插件版本:  2.1.0
* react-native 版本： 0.47.1

## 期望效果

告诉我们你希望达到什么效果。

npm run configureJPush 执行成功

## 实际效果

告诉我们实际是什么效果。

出错：

```
fs.js:953
  binding.stat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, stat '/Users/xwartz/work/xxx/xx-v2/ios/DerivedData/ModuleCache/3SUBPZP8UCL3N/Foundation-3DFYNEBRQSXST.pcm.lock'
    at Object.fs.statSync (fs.js:953:11)
    at eachFileSync (/Users/xwartz/work/xxx/xxx-v2/node_modules/jpush-react-native/JPushConfiguration.js:205:17)
    at /Users/xwartz/work/xxx/xxx-v2/node_modules/jpush-react-native/JPushConfiguration.js:213:4
    at Array.forEach (native)
    at eachFileSync (/Users/xwartz/work/xxx/xxx-v2/node_modules/jpush-react-native/JPushConfiguration.js:212:9)
    at /Users/xwartz/work/xxx/xxx-v2/node_modules/jpush-react-native/JPushConfiguration.js:213:4
    at Array.forEach (native)
    at eachFileSync (/Users/xwartz/work/xxx/xxx-v2/node_modules/jpush-react-native/JPushConfiguration.js:212:9)
    at /Users/xwartz/work/xxx/xxx-v2/node_modules/jpush-react-native/JPushConfiguration.js:213:4
    at Array.forEach (native)
```

其实存在这个文件的：

![image](https://user-images.githubusercontent.com/4149827/31575020-67a11686-b0a2-11e7-9dd5-36cf8134c32e.png)

## 重现步骤

npm run configureJPush <yourAppKey> <yourModuleName>

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by xwartz** [comment]
删除 Foundation-3DFYNEBRQSXST.pcm.lock 文件，ok了
