### ISSUE TITLE
Unable to start receiver cn.jpush.reactnativejpush.JPushModule$JPushReceiver

### ISSUE THREAD

**Issue by cq920702** [jpush/jpush-react-native#380]
## 你的运行环境

* 插件版本:"jcore-react-native": "^1.1.3",
                 "jpush-react-native": "^1.6.6",
* react-native 版本：
0.43.4

## 期望效果

告诉我们你希望达到什么效果。

正常收到人工语音

## 实际效果

告诉我们实际是什么效果。

用了友盟统计，添加了安卓自定义语音功能，上线后，友盟里列出了很多错误，全是提示
java.lang.RuntimeException: Unable to start receiver cn.jpush.reactnativejpush.JPushModule$JPushReceiver: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(pri=0 contentView=com.bagongli.service/0x1090084 vibrate=null sound=android.resource://com.bagongli.service/2131165192 defaults=0x0 flags=0x0 color=0x00000000 vis=PRIVATE)

## 重现步骤

  1. ...
  2. ...
  3. ...
  4. ...

## Debug logs

包括 Android 或 iOS 的日志：
java.lang.RuntimeException: Unable to start receiver cn.jpush.reactnativejpush.JPushModule$JPushReceiver: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(pri=0 contentView=com.bagongli.service/0x1090084 vibrate=null sound=android.resource://com.bagongli.service/2131165192 defaults=0x0 flags=0x0 color=0x00000000 vis=PRIVATE)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2767)
	at android.app.ActivityThread.access$1800(ActivityThread.java:165)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1453)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5621)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(pri=0 contentView=com.bagongli.service/0x1090084 vibrate=null sound=android.resource://com.bagongli.service/2131165192 defaults=0x0 flags=0x0 color=0x00000000 vis=PRIVATE)
	at android.app.NotificationManager.notify(NotificationManager.java:222)
	at android.app.NotificationManager.notify(NotificationManager.java:194)
	at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.processCustomMessage(JPushModule.java:610)
	at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:475)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2760)
	... 8 more
java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(pri=0 contentView=com.bagongli.service/0x1090084 vibrate=null sound=android.resource://com.bagongli.service/2131165192 defaults=0x0 flags=0x0 color=0x00000000 vis=PRIVATE)
	at android.app.NotificationManager.notify(NotificationManager.java:222)
	at android.app.NotificationManager.notify(NotificationManager.java:194)
	at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.processCustomMessage(JPushModule.java:610)
	at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:475)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2760)
	at android.app.ActivityThread.access$1800(ActivityThread.java:165)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1453)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5621)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by KenChoi1992** [comment]
@cq920702 你构建自定义通知？看日志没有加上 small icon

**Comment by KenChoi1992** [comment]
@cq920702 没有回复先关闭了
