### ISSUE TITLE
android 手机点击通知无法唤起 App

### ISSUE THREAD

**Issue by mx1700** [jpush/jpush-react-native#458]
## 你的运行环境

* 插件版本:2.1.11
* react-native 版本：0.52
* 手机：小米 mix 2，MIUI 9，基于 android 8.0

## 期望效果

App 后台时收到 PUSH，点击通知打开 App

## 实际效果

点击通知没有任何反应，只是通知消失了

## 重现步骤

我是用的官方的 example ，配置 appkey & applicationId 后，从 jpush 后台发送通知
手机可以正常接收到
如果 App 处于前台，点击通知则会打开 second 页面
如果 App 处于后台，则点击没有反应，App 不会被唤起

## Debug logs

I/JPushModule: 收到推送下来的通知: 123
I/JPushModule: extras: {}
I/JPushModule: Sending event : receiveNotification
D/JPushModule: 用户点击打开了通知
I/Timeline: Timeline: Activity_launch_request time:157692510
W/System.err:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1941)
W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1619)
W/System.err:     at android.app.ContextImpl.startActivity(ContextImpl.java:872)
W/System.err:     at android.app.ContextImpl.startActivity(ContextImpl.java:849)
W/System.err:     at android.content.ContextWrapper.startActivity(ContextWrapper.java:376)
W/System.err:     at android.content.ContextWrapper.startActivity(ContextWrapper.java:376)
W/System.err:     at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:550)
W/System.err:     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3271)
W/System.err:     at android.app.ActivityThread.-wrap17(Unknown Source:0)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1694)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err:     at android.os.Looper.loop(Looper.java:164)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6665)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
I/JPushModule: Shouldn't access here

**Comment by mx1700** [comment]
找到原因了，因为改了 applicationId，详细见链接
https://www.jianshu.com/p/504d28cd2651
