### ISSUE TITLE
JPushConfiguration.js cannot find

### ISSUE THREAD

**Issue by Ironpeterj** [jpush/jpush-react-native#474]
## 你的运行环境

* 插件版本:  "jcore-react-native": "^1.2.5",
    "jpush-react-native": "^2.1.12",
* react-native 版本：0.44.1

## 期望效果

npm run configureJPush myappKey app正常

## 实际效果
npm run configureJPush myappKey app 报错
module.js:557
    throw err;
    ^

Error: Cannot find module '/Users/hfjy/LearningParentPhone/node_modules/jpush-react-native/JPushConfiguration.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

## 重现步骤

1. ...npm install jcore-react-native -save npm intall jpush-react-native --save
2. ...npm run configureJPush myappKey app
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by huangminlinux** [comment]
最新版本已经不需要执行这个脚本了。
直接 link 有提示输入相关参数。

**Comment by Ironpeterj** [comment]
正解，谢谢

**Comment by Ironpeterj** [comment]
0.44.1版本的react-native 运行react-native link的时候报错（0.52.0的rn没问题）：
? Input the appKey for JPush 

/Users/hfjy/Documents/GitHubProjects/TestJpush/node_modules/jpush-react-native/scripts/patch.js:13
inquirer.prompt(questions).then(answers => {
                           ^

TypeError: inquirer.prompt(...).then is not a function
    at Object.<anonymous> (/Users/hfjy/Documents/GitHubProjects/TestJpush/node_modules/jpush-react-native/scripts/patch.js:13:28)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
/Users/hfjy/Documents/GitHubProjects/TestJpush/node_modules/react-native/local-cli/core/makeCommand.js:29
        throw new Error(`Error occured during executing "${command}" command`);
        ^

Error: Error occured during executing "node node_modules/jpush-react-native/scripts/patch" command
    at ChildProcess.prelink (/Users/hfjy/Documents/GitHubProjects/TestJpush/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

**Comment by huangminlinux** [comment]
检查一下 inquirer 这个依赖安装了没

**Comment by Ironpeterj** [comment]
装了是0.12.0版本，我在主工程目录重新install inquirer（5.2.0）后可以了

**Comment by Ironpeterj** [comment]
为什么每次link都要提示input appkey？这个有点坑啊

**Comment by huangminlinux** [comment]
单独升级 inquirer 试试。

只有第一次安装的时候需要 link ，没有频繁 link 的需要把。

**Comment by Ironpeterj** [comment]
我添加了新库，需要link的时候就会提示这个，岂不是有点麻烦吗？

**Comment by huangminlinux** [comment]
react-native link 插件名就行。

**Comment by pheromone** [comment]
为何我在安装了库之后,link之后弹出输入appkey,输入之后回车就一直卡住呢?
![image](https://user-images.githubusercontent.com/14305431/41085323-3b26ff7c-6a69-11e8-81b6-07ac521f0600.png)
