### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by sapjax** [jpush/jpush-react-native#478]
## 你的运行环境

* 设备： MI6、Mi Note2、MI 5s、MI MAX 2、 xiaomi-1s、 OPPO R11s Plus
* android 版本: 7.0、7.1.1、4.2.4
* 插件版本:2.1.7
* react-native 版本：0.51.0

## 日志
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.util.SparseArray.get(int)' on a null object reference
       at cn.jpush.reactnativejpush.JPushModule$MyJPushMessageReceiver.onTagOperatorResult(JPushModule.java:595)
       at cn.jpush.android.a.a$a.run(SourceFile:73)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by sapjax** [comment]
还有另外一个错误：
设备： OPPO CPH1609、 OPPO R9m、changhong S01
android 版本: 5.1、6.0


```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.util.SparseArray.put(int, java.lang.Object)' on a null object reference
       at cn.jpush.reactnativejpush.JPushModule.setTags(JPushModule.java:203)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:224)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by KenChoi1992** [comment]
@sapjax 新版本修复了
