### ISSUE TITLE
missing script: configureJPush

### ISSUE THREAD

**Issue by edgargao** [jpush/jpush-react-native#492]
## 你的运行环境

* 插件版本:
* react-native 版本：0.44.3

## 期望效果

执行npm run configureJPush命令成功

## 实际效果

执行npm run configureJPush命令时报错，错误信息如下：
missing script: configureJPush。

我的是window7系统，已安装android开发环境。react native版本是0.44.3，node.js版本是8.4.0，npm版本是4.2.0。

**Comment by huangminlinux** [comment]
新版本插件将 configureJPush 移动到 link 操作中， 执行 react-native link 就可以了。

**Comment by edgargao** [comment]
@huangminlinux 
执行link时报错。
E:\rn\git\md_app>react-native link
Scanning 709 folders for symlinks in E:\rn\git\md_app\node_modules (22ms)
rnpm-install info iOS module jcore-react-native is already linked
? Input the appKey for JPush

E:\rn\git\md_app\node_modules\jpush-react-native\scripts\patch.js:13
inquirer.prompt(questions).then(answers => {
                           ^

TypeError: inquirer.prompt(...).then is not a function
    at Object.<anonymous> (E:\rn\git\md_app\node_modules\jpush-react-native\scripts\patch.js:13:28)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
E:\rn\git\md_app\node_modules\react-native\local-cli\core\makeCommand.js:29
        throw new Error(`Error occured during executing "${command}" command`);
        ^

Error: Error occured during executing "node node_modules/jpush-react-native/scripts/patch" command
    at ChildProcess.prelink (E:/rn/git/md_app/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by huangminlinux** [comment]
可以参考这个issue #474
