### ISSUE TITLE
React-Native Link Exception

### ISSUE THREAD

**Issue by ssqyht** [jpush/jpush-react-native#499]
## 你的运行环境
Mac 

* 插件版本:
* react-native 版本：0.45.1

## 期望效果

React-Native link 执行成功

## 实际效果

执行失败：异常信息如下：

admin:ProjectName admin$ react-native link
Scanning 631 folders for symlinks in /Users/admin/git/project/demo/rn/ProjectName/node_modules (9ms)
rnpm-install info iOS module jcore-react-native is already linked 
? Input the appKey for JPush 

/Users/admin/git/project/demo/rn/ProjectName/node_modules/jpush-react-native/scripts/patch.js:13
inquirer.prompt(questions).then(answers => {
                           ^

TypeError: inquirer.prompt(...).then is not a function
    at Object.<anonymous> (/Users/admin/git/project/demo/rn/ProjectName/node_modules/jpush-react-native/scripts/patch.js:13:28)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
/Users/admin/git/project/demo/rn/ProjectName/node_modules/react-native/local-cli/core/makeCommand.js:29
        throw new Error(`Error occured during executing "${command}" command`);
        ^

Error: Error occured during executing "node node_modules/jpush-react-native/scripts/patch" command
    at ChildProcess.prelink (/Users/admin/git/project/demo/rn/ProjectName/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
admin:ProjectName admin$ 

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by huangminlinux** [comment]
可以参考这个 [issue( https://github.com/jpush/jpush-react-native/issues/474#issuecomment-378174314)
