### ISSUE TITLE
Unable to start receiver cn.jpush.reactnativejpush.JPushModule$JPushReceiver: java.lang.NullPointerException

### ISSUE THREAD

**Issue by ljunb** [jpush/jpush-react-native#55]
Android端APP在收到一条推送消息后，在后台继续推送第二天消息，APP就闪退了。我在控制台捕获到的信息是这样的：Unable to start receiver cn.jpush.reactnativejpush.JPushModule$JPushReceiver: java.lang.NullPointerException。
因为我对Android不大熟悉，期待回复，或者给予解决问题的思路！

**Comment by KenChoi1992** [comment]
@ljunb 有没有更多日志？

**Comment by KenChoi1992** [comment]
@ljunb 刚才我运行了demo，没有重现到你的情况，有没有详细的操作步骤？

**Comment by ljunb** [comment]
现在又重现不了了。之前是没有添加JSPackage到MainActivity操作的，现在添加之后，不管有没在JS调用JPushModule.initPush()方法，输出这个警告：
10-18 14:50:07.213 7544-7544/com.mp1 W/JPush: [SharePreferenceProcess] context is null, in SharePreferenceProcess.init

**Comment by ljunb** [comment]
@KenChoi1992 设备信息是可以获取到的，但是现在getRegistrationID返回的是空，这个是因为gradle版本原因吗？我项目的版本是2.0.0的

**Comment by ljunb** [comment]
@KenChoi1992 现在莫名好了~未找到原因

**Comment by JimmyDaddy** [comment]
```
java.lang.RuntimeException: Unable to start receiver cn.jpush.reactnativejpush.JPushModule$JPushReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.react.bridge.JavaScriptModule com.facebook.react.bridge.ReactApplicationContext.getJSModule(java.lang.Class)' on a null object reference
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2997)
	at android.app.ActivityThread.access$1900(ActivityThread.java:192)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:5929)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.react.bridge.JavaScriptModule com.facebook.react.bridge.ReactApplicationContext.getJSModule(java.lang.Class)' on a null object reference
	at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:251)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2990)
	... 9 more
java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.react.bridge.JavaScriptModule com.facebook.react.bridge.ReactApplicationContext.getJSModule(java.lang.Class)' on a null object reference
	at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:251)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2990)
	at android.app.ActivityThread.access$1900(ActivityThread.java:192)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:5929)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
```

**Comment by JimmyDaddy** [comment]
我遇到同样的问题，并且一直没好，能解决么？ @KenChoi1992

**Comment by xuetongiqn** [comment]
+1 同样问题
