### ISSUE TITLE
[Android]杀掉app后点击已有的消息推送，app启动后crash

### ISSUE THREAD

**Issue by pampang** [jpush/jpush-react-native#56]
报错信息如下：

```
10-18 17:02:41.920 10326-10326/com.shefenqi.mall D/JPushModule: 用户点击打开了通知
10-18 17:02:41.921 10326-10326/com.shefenqi.mall W/dalvikvm: Exception Ljava/lang/RuntimeException; thrown while initializing Lcom/facebook/react/bridge/ReactBridge;
10-18 17:02:41.921 10326-10326/com.shefenqi.mall W/dalvikvm: Exception Ljava/lang/ExceptionInInitializerError; thrown while initializing Lcom/facebook/react/bridge/NativeMap;
10-18 17:02:41.921 10326-10326/com.shefenqi.mall D/AndroidRuntime: Shutting down VM
10-18 17:02:41.921 10326-10326/com.shefenqi.mall W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4165ed40)
10-18 17:02:41.953 10326-10333/com.shefenqi.mall I/dalvikvm: Total arena pages for JIT: 11
10-18 17:02:41.954 10326-10333/com.shefenqi.mall I/dalvikvm: Total arena pages for JIT: 12
10-18 17:02:41.954 10326-10333/com.shefenqi.mall I/dalvikvm: Total arena pages for JIT: 13
10-18 17:02:42.308 10326-10333/com.shefenqi.mall I/dalvikvm: Total arena pages for JIT: 14
10-18 17:02:42.308 10326-10333/com.shefenqi.mall I/dalvikvm: Total arena pages for JIT: 15
10-18 17:02:42.308 10326-10333/com.shefenqi.mall I/dalvikvm: Total arena pages for JIT: 16
10-18 17:02:42.309 10326-10333/com.shefenqi.mall I/dalvikvm: Total arena pages for JIT: 17
10-18 17:02:42.309 10326-10333/com.shefenqi.mall I/dalvikvm: Total arena pages for JIT: 18
10-18 17:02:42.309 10326-10333/com.shefenqi.mall I/dalvikvm: Total arena pages for JIT: 19
10-18 17:02:42.309 10326-10333/com.shefenqi.mall I/dalvikvm: Total arena pages for JIT: 20
10-18 17:02:42.309 10326-10333/com.shefenqi.mall I/dalvikvm: Total arena pages for JIT: 21
10-18 17:02:42.310 10326-10333/com.shefenqi.mall I/dalvikvm: Total arena pages for JIT: 22
10-18 17:02:42.974 10326-10326/com.shefenqi.mall E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.shefenqi.mall, PID: 10326
                                                                   java.lang.ExceptionInInitializerError
                                                                       at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22)
                                                                       at com.facebook.react.bridge.Arguments.createMap(Arguments.java:29)
                                                                       at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:119)
                                                                       at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:255)
                                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2446)
                                                                       at android.app.ActivityThread.access$1700(ActivityThread.java:139)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5102)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                    Caused by: java.lang.RuntimeException: SoLoader.init() not yet called
                                                                       at com.facebook.soloader.SoLoader.assertInitialized(SoLoader.java:234)
                                                                       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:169)
                                                                       at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:39)
                                                                       at com.facebook.react.bridge.ReactBridge.<clinit>(ReactBridge.java:31)
                                                                       at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22) 
                                                                       at com.facebook.react.bridge.Arguments.createMap(Arguments.java:29) 
                                                                       at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:119) 
                                                                       at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:255) 
                                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2446) 
                                                                       at android.app.ActivityThread.access$1700(ActivityThread.java:139) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5102) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                       at dalvik.system.NativeStart.main(Native Method) 
```

看了一下源码，感觉像是在重写`onReceive`方法的时候，如果app未启动过，执行`WritableMap map = Arguments.fromBundle(bundle);`会导致上述的错误。

```
10-18 17:02:41.920 10326-10326/com.shefenqi.mall D/JPushModule: 用户点击打开了通知
10-18 17:02:41.921 10326-10326/com.shefenqi.mall W/dalvikvm: Exception Ljava/lang/RuntimeException; thrown while initializing Lcom/facebook/react/bridge/ReactBridge;
10-18 17:02:41.921 10326-10326/com.shefenqi.mall W/dalvikvm: Exception Ljava/lang/ExceptionInInitializerError; thrown while initializing Lcom/facebook/react/bridge/NativeMap;
10-18 17:02:41.921 10326-10326/com.shefenqi.mall D/AndroidRuntime: Shutting down VM
```

**Comment by pampang** [comment]
???
请问这个issue没有人回答吗？
这可能是repo里面的代码问题哦？

**Comment by KenChoi1992** [comment]
@pampang 你的意思是可能是 react-native 本身的问题？

**Comment by pampang** [comment]
```
      } else if (JPushInterface.ACTION_NOTIFICATION_OPENED.equals(data.getAction())) {
                Logger.d(TAG, "用户点击打开了通知");
                WritableMap map = Arguments.fromBundle(bundle);
                mRAC.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                        .emit("openNotification", map);
                Intent intent = new Intent();
                if (mModule != null && mModule.mContext != null) {
                    intent.setClass(context, mModule.mContext.getClass());
                    Logger.d(TAG, "context.getClass: " + mModule.mContext.getClass());
                    intent.putExtras(bundle);
                    intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                    context.startActivity(intent);
                } else {
                    String packageName = context.getApplicationContext().getPackageName();
                    Intent launchIntent = context.getPackageManager().getLaunchIntentForPackage(packageName);
                    launchIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_RESET_TASK_IF_NEEDED);
                    launchIntent.putExtras(bundle);
                    context.startActivity(launchIntent);
                }
            }
```

这是在
https://github.com/jpush/jpush-react-native/blob/master/android/src/main/java/cn/jpush/reactnativejpush/JPushModule.java
的代码，在`WritableMap map = Arguments.fromBundle(bundle);`一行中的Argument似乎因为尚未初始化而会导致程序崩溃

**Comment by KenChoi1992** [comment]
@pampang  这个 Arguments  就是 react-native 提供的：import com.facebook.react.bridge.Arguments;

**Comment by pampang** [comment]
以下讨论都在Android下发生：
app在前台的时候，点击推送是不会有问题的。
问题是在于我“杀掉app后点击已有的消息推送，app启动后crash”，而看这个crash感觉与Argument优点干系，但更深入的研究并没有做。
但按理说，点击已有的消息推送，应该是能够正常的进入到APP的呀？
而目前是点击就报错，弹出提示框“APP已经被终止”

**Comment by KenChoi1992** [comment]
杀掉 app 后，消息栏中的消息应该被清空才对吧，除非有别的推送拉起了，否则现有的通知应该会被清空才对。

**Comment by pampang** [comment]
我手上android 4.*的手机，包括原生系统、三星定制系统，在杀掉app时都没有清空推送，此时点击推送就会出现上述crash

**Comment by KenChoi1992** [comment]
@pampang 新版本我升级了 jpush，你试试看新版本能不能清空通知。我这边测试 Android6.0 的手机杀掉进程是可以清空的。

**Comment by KenChoi1992** [comment]
在退出时可以手动调这个接口： JPushModule.clearAllNotifications() 清除所有的通知。
