### ISSUE TITLE
Android 调用setStyleCustom 奔溃

### ISSUE THREAD

**Issue by lfyhhb116** [jpush/jpush-react-native#602]
## 你的运行环境

* 插件版本: 
 "jcore-react-native": "^1.2.7",
    "jpush-react-native": "^2.2.6",
* react-native 版本：
"react-native": "0.55.4",

## 期望效果
 正常运行

告诉我们你希望达到什么效果。

## 实际效果
出现崩溃

告诉我们实际是什么效果。

## 重现步骤

1. ... 打开Android应用
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
at cn.jpush.reactnativejpush.IdHelper.getLayout(IdHelper.java:9)
at cn.jpush.reactnativejpush.JPushModule.setStyleCustom(JPushModule.java:405)
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:891)
at android.os.Handler.dispatchMessage(Handler.java:102)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
at android.os.Looper.loop(Looper.java:207)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
at java.lang.Thread.run(Thread.java:784)

**Comment by JoshLipan** [comment]
设置[自定义样式](https://github.com/jpush/jpush-react-native/blob/master/android/src/main/java/cn/jpush/reactnativejpush/JPushModule.java#L402)需要在 Android 原生目录建立自定义布局，布局和控件id都有限制

**Comment by lfyhhb116** [comment]
嗯嗯  OK  谢谢
