### ISSUE TITLE
cn.jpush.reactnativejpush.JPushModule.sendEvent 报错 

### ISSUE THREAD

**Issue by niuniubuniu** [jpush/jpush-react-native#609]
## 你的运行环境

* 插件版本:
    "react-native": "0.57.5",
    "jcore-react-native": "^1.3.1",
    "jpush-react-native": "^2.5.1",
## 期望效果

正常使用极光推送功能 不崩溃

## 实际效果

个别手机出现崩溃

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs
错误详情 1:
手机型号 KIW-TL00
java.lang.RuntimeException: Could not invoke JPushModule.notifyJSDidLoad
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:743)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:150)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
	at java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	... 8 more
Caused by: java.lang.IncompatibleClassChangeError: Class 'java.lang.VirtualMachineError' does not implement interface 'java.lang.Class' in call to 'byte byte.()' (declaration of 'java.lang.Throwable' appears in /system/framework/core-libart.jar)
	at cn.jpush.reactnativejpush.JPushModule.sendEvent(JPushModule.java:223)
	at cn.jpush.reactnativejpush.JPushModule.notifyJSDidLoad(JPushModule.java:173)
	... 10 more

错误详情 2：
手机型号 oppo A57t ，KIW-TL00
系统版本号 6.0.1
java.lang.IncompatibleClassChangeError: Class 'java.lang.VirtualMachineError' does not implement interface 'java.lang.Class' in call to 'byte byte.()' (declaration of 'java.lang.Throwable' appears in /system/framework/core-libart.jar)
	at cn.jpush.reactnativejpush.JPushModule.sendEvent(JPushModule.java:223)
	at cn.jpush.reactnativejpush.JPushModule.access$400(JPushModule.java:51)
	at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:669)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2760)
	at android.app.ActivityThread.access$1800(ActivityThread.java:165)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1453)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5621)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by JoshLipan** [comment]
更新至 v2.5.3 再试试

**Comment by HHuiHao** [comment]
更新至 v2.5.3 能解决吗？

**Comment by xwartz** [comment]
@JoshLipan   更新至 v2.5.3 还是复现，不过出现这个 crash 的都是 6.0 的系统

**Comment by xwartz** [comment]
看起来是网易 mumu 模拟器造成的？https://community.jiguang.cn/t/topic/31407/4?u=xwartz

![image](https://user-images.githubusercontent.com/4149827/65028208-480dba80-d96e-11e9-9aa0-53f6752df323.png)
