### ISSUE TITLE
error: cannot find symbol method registerActivityLifecycle(MainApplication)

### ISSUE THREAD

**Issue by x13945** [jpush/jpush-react-native#677]
## 你的运行环境

* 插件版本:

  ```json
   "dependencies": {
     "jcore-react-native": "^1.3.7",
     "jpush-react-native": "^2.5.9",
     "react": "16.8.6",
     "react-native": "0.60.5"
   },
  
  ```

  

## 期望效果

可以正常运行当前仓库中example的Android版本

## 实际效果

打包运行失败

## 重现步骤

1. clone官方工程

   ```shell
   git clone https://github.com/jpush/jpush-react-native.git
   ```

   

2. 在命令行中进入example目录

   ```shell
   cd jpush-react-native/example
   ```

   

3. 运行Android版本的示例

   ```shell
   react-native run-android
   ```

   

## Debug logs

```shell
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/shaw/Downloads/jpush-react-native-master/example/android/app/src/main/java/com/example/MainApplication.java:47: error: cannot find symbol
    JPushModule.registerActivityLifecycle(this);
               ^
  symbol:   method registerActivityLifecycle(MainApplication)
  location: class JPushModule
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:13)
    at runOnAllDevices (/Users/shaw/Downloads/jpush-react-native-master/example/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:74:39)
    at buildAndRun (/Users/shaw/Downloads/jpush-react-native-master/example/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at then.result (/Users/shaw/Downloads/jpush-react-native-master/example/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Yzhoufelix** [comment]
同样的问题，求解答

**Comment by webxiaohe** [comment]
I had the same problem

**Comment by jerryzyz008** [comment]
参考 [https://github.com/jpush/jpush-react-native/issues/671#issuecomment-534838570](url)

**Comment by excitedcat** [comment]
同样的问题，求解答

**Comment by ym91** [comment]
可以 试试  cd android 然后 ./gradlew clean
再 react-native run-android

**Comment by x13945** [comment]
> 可以 试试 cd android 然后 ./gradlew clean
> 再 react-native run-android

不行的，因为当前jpush的Android native中不存在这个api导致的。感觉是example用了未发布的api，并提交到了github。只能等待仓库维护者修改了。

**Comment by ym91** [comment]
> > 可以 试试 cd android 然后 ./gradlew clean
> > 再 react-native run-android
> 
> 不行的，因为当前jpush的Android native中不存在这个api导致的。感觉是example用了未发布的api，并提交到了github。只能等待仓库维护者修改了。

但是我能运行呀。。。

**Comment by x13945** [comment]
commit: 8f183f447ca75f66c7af7dfad8b1554db2959ab9 修复了这个问题，并且在commit： bdd9adeb73fe8384c3a65073da0ad617d5752fea 中merge到了主分支。

因此该问题已被修复，那我就关闭该issue了
