### ISSUE TITLE
[Android]运行Demo程序，在64位下闪退

### ISSUE THREAD

**Issue by lookerson** [jpush/jpush-react-native#73]
您好，我运行了这个仓库的example里的代码，运行步骤如下：
```
npm install
react-native run-android
```
在手机上点击PushDemo程序，程序启动后闪退，使用adb logcat查看日志，如下：
```
E/art     (22903): dlopen("/data/data/com.pushdemo/lib-main/libgnustl_shared.so", RTLD_LAZY) failed: dlopen failed: "/data/data/com.pushdemo/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit
D/AndroidRuntime(22903): Shutting down VM
E/AndroidRuntime(22903): FATAL EXCEPTION: main
E/AndroidRuntime(22903): Process: com.pushdemo, PID: 22903
E/AndroidRuntime(22903): java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.pushdemo/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit
E/AndroidRuntime(22903):        at java.lang.Runtime.load(Runtime.java:331)
E/AndroidRuntime(22903):        at java.lang.System.load(System.java:981)
E/AndroidRuntime(22903):        at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
E/AndroidRuntime(22903):        at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
E/AndroidRuntime(22903):        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
E/AndroidRuntime(22903):        at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
E/AndroidRuntime(22903):        at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
E/AndroidRuntime(22903):        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
E/AndroidRuntime(22903):        at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
E/AndroidRuntime(22903):        at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
E/AndroidRuntime(22903):        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
E/AndroidRuntime(22903):        at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
E/AndroidRuntime(22903):        at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
E/AndroidRuntime(22903):        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
E/AndroidRuntime(22903):        at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
E/AndroidRuntime(22903):        at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
E/AndroidRuntime(22903):        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
E/AndroidRuntime(22903):        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)
E/AndroidRuntime(22903):        at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
E/AndroidRuntime(22903):        at com.facebook.react.bridge.ReactBridge.<clinit>(ReactBridge.java:20)
E/AndroidRuntime(22903):        at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
E/AndroidRuntime(22903):        at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22)
E/AndroidRuntime(22903):        at com.facebook.react.JSCConfig$1.getConfigMap(JSCConfig.java:14)
E/AndroidRuntime(22903):        at com.facebook.react.XReactInstanceManagerImpl.onJSBundleLoadedFromServer(XReactInstanceManagerImpl.java:727)
E/AndroidRuntime(22903):        at com.facebook.react.XReactInstanceManagerImpl.recreateReactContextInBackgroundInner(XReactInstanceManagerImpl.java:388)
E/AndroidRuntime(22903):        at com.facebook.react.XReactInstanceManagerImpl.createReactContextInBackground(XReactInstanceManagerImpl.java:359)
E/AndroidRuntime(22903):        at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:223)
E/AndroidRuntime(22903):        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:101)
E/AndroidRuntime(22903):        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:91)
E/AndroidRuntime(22903):        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54)
E/AndroidRuntime(22903):        at android.app.Activity.performCreate(Activity.java:6041)
E/AndroidRuntime(22903):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
E/AndroidRuntime(22903):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2285)
E/AndroidRuntime(22903):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2394)
E/AndroidRuntime(22903):        at android.app.ActivityThread.access$800(ActivityThread.java:154)
E/AndroidRuntime(22903):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
E/AndroidRuntime(22903):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(22903):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(22903):        at android.app.ActivityThread.main(ActivityThread.java:5276)
E/AndroidRuntime(22903):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22903):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(22903):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
E/AndroidRuntime(22903):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
```
根据提示的信息来看，貌似错误原因是二进制库是32位而我的CPU是64位。

我使用的手机是红米Note3全网通版本，CPU是高通骁龙650，运行的系统是基于Android 5.1的MIUI 8。

我使用的React Native版本是0.34.1。

谢谢。

**Comment by KenChoi1992** [comment]
插件里的 so 文件都齐了的，是否 package.json 没有加上依赖？试试加上 --save ?

**Comment by lookerson** [comment]
我之前是直接通过clone这个仓库，然后进入到example文件夹下，`npm install`后使用`react-native run-android`运行，结果提示上面这个错误。后来，我自己新建一个项目，按照文档所说进行配置，就没有任何问题。
具体为什么会这样，我也不太清楚。
非常感谢您。

**Comment by KenChoi1992** [comment]
@lookerson 你新建的项目是否加了这个：
```
...
defaultConfig {
...
    ndk {
        abiFilters "armeabi-v7a", "x86"
    }
}

```

**Comment by lookerson** [comment]
@KenChoi1992 是的，新建的项目里自动加了这个

**Comment by KenChoi1992** [comment]
那就是这个问题了，加上后就没事了。

**Comment by lookerson** [comment]
@KenChoi1992 是的，应该就是这个问题。
非常感谢 ^_^

**Comment by isuccess188** [comment]
@KenChoi1992 请问在Eclipse中怎么添加您所说的这个文件
