### ISSUE TITLE
[Android] App crash scenario

### ISSUE THREAD

**Issue by devhyunjae** [jpush/jpush-react-native#78]
1. receive a push message
2. clean my phone's memory
3. touch the received push message

4. app crashes with this message

```
11-28 11:44:40.455 8147-8147/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.hsmobile, PID: 8147
                                                 java.lang.ExceptionInInitializerError
                                                     at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
                                                     at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22)
                                                     at com.facebook.react.bridge.Arguments.createMap(Arguments.java:29)
                                                     at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:119)
                                                     at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:255)
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3700)
                                                     at android.app.ActivityThread.access$2000(ActivityThread.java:229)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1903)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                  Caused by: java.lang.RuntimeException: SoLoader.init() not yet called
                                                     at com.facebook.soloader.SoLoader.assertInitialized(SoLoader.java:335)
                                                     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:238)
                                                     at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
                                                     at com.facebook.react.bridge.ReactBridge.<clinit>(ReactBridge.java:20)
                                                     at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24) 
                                                     at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22) 
                                                     at com.facebook.react.bridge.Arguments.createMap(Arguments.java:29) 
                                                     at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:119) 
                                                     at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:255) 
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3700) 
                                                     at android.app.ActivityThread.access$2000(ActivityThread.java:229) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1903) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
```

you should track this one.

**at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:255)**

**Comment by KenChoi1992** [comment]
@devhyunjae This method is already provided. Probably you should call clearAllNotifications when exit App. For example, 
```
componentWillUnmount() {
    JPushModule.clearAllNotifications();
}
```

**Comment by devhyunjae** [comment]
@KenChoi1992 Clearing the push message is the only solution? That doesn't make sense...😰

You are saying that **jpush message -> to my app** only works when the app is running?(foreground or background)

**Comment by KenChoi1992** [comment]
@devhyunjae https://github.com/facebook/react-native/issues/10379 This issue seems occurred same problem as you did.  JPushModule.java line 255 is that:
```
WritableMap map = Arguments.fromBundle(bundle);
```
This method is provided by facebook's react bridge. I don't know the solution for now, you can take my advice for temporary solution.

**Comment by KenChoi1992** [comment]
@devhyunjae  It seems there is a solution: call   SoLoader.init(this, /* native exopackage */ false) in you Application class. See this for detail: https://github.com/facebook/react-native/commit/0907ef668921a63f3ed447d442f84c54a5a20452

**Comment by devhyunjae** [comment]
Now I am having different error 😢
```
11-28 17:56:21.175 13664-13664/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.hsmobile, PID: 13664
                                                   java.lang.RuntimeException: Unable to start receiver cn.jpush.reactnativejpush.JPushModule$JPushReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.react.bridge.JavaScriptModule com.facebook.react.bridge.ReactApplicationContext.getJSModule(java.lang.Class)' on a null object reference
                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3707)
                                                       at android.app.ActivityThread.access$2000(ActivityThread.java:229)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1903)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.react.bridge.JavaScriptModule com.facebook.react.bridge.ReactApplicationContext.getJSModule(java.lang.Class)' on a null object reference
                                                       at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:259)
                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3700)
                                                       at android.app.ActivityThread.access$2000(ActivityThread.java:229) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1903) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by devhyunjae** [comment]
seems like there is a way with this
http://facebook.github.io/react-native/docs/headless-js-android.html

**Comment by KenChoi1992** [comment]
@devhyunjae If it is convenient for you，you can add this:
```
public static class JPushReceiver extends BroadcastReceiver {

    public JPushReceiver() {
            HeadlessJsTaskService.acquireWakeLockNow(mModule.getReactApplicationContext());
    }
   ...
```
in JPushModule.java to see if it works or not. I will test it later. :)

**Comment by KenChoi1992** [comment]
@devhyunjae  Hey,  are you resolve this problem ? Since you didn't reply after these days, I assume that you've already resolved. Closing issue now.

**Comment by devhyunjae** [comment]
@KenChoi1992 nope, still having the same problem :( Like you have mentioned at the first-time, this is the react-native issue, so I just have to wait until there will be good new at the next release...

**Comment by pampang** [comment]
#56

**Comment by pampang** [comment]
Not only the "UNCLEAR NOTIFICATIONS" cause this problems. The deamon service wakes up app(but RN will not start initialization right now), and if a new notifications comes after the app is waken up, crash comes too.
In Chinese translation: app被相互唤醒之后，新推送抵达，依然会导致该crash产生。

**Comment by KenChoi1992** [comment]
@pampang 加了上面的那句也不行吗？

**Comment by KenChoi1992** [comment]
@pampang  重新看了下 React Native 的文档，感觉要重写 JPush 的 Service，专门为 React Native 插件打包一个版本，只是这样的话，我们需要商榷一下。

**Comment by pampang** [comment]
刚刚走查了一遍，上述的解决方法都用过，总结如下：
1、如果没有写任何代码，会报错：
```
11-28 11:44:40.455 8147-8147/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.hsmobile, PID: 8147
                                                 java.lang.ExceptionInInitializerError
                                                     at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
                                                     at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22)
                                                     at com.facebook.react.bridge.Arguments.createMap(Arguments.java:29)
                                                     at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:119)
                                                     at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:255)
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3700)
                                                     at android.app.ActivityThread.access$2000(ActivityThread.java:229)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1903)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                  Caused by: java.lang.RuntimeException: SoLoader.init() not yet called
                                                     at com.facebook.soloader.SoLoader.assertInitialized(SoLoader.java:335)
                                                     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:238)
                                                     at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
                                                     at com.facebook.react.bridge.ReactBridge.<clinit>(ReactBridge.java:20)
                                                     at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24) 
                                                     at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22) 
                                                     at com.facebook.react.bridge.Arguments.createMap(Arguments.java:29) 
                                                     at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:119) 
                                                     at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:255) 
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3700) 
                                                     at android.app.ActivityThread.access$2000(ActivityThread.java:229) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1903) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
```

2、如果在MainApplication下初始化了`SoLoader.init()`，报错如下：
```
11-28 17:56:21.175 13664-13664/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.hsmobile, PID: 13664
                                                   java.lang.RuntimeException: Unable to start receiver cn.jpush.reactnativejpush.JPushModule$JPushReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.react.bridge.JavaScriptModule com.facebook.react.bridge.ReactApplicationContext.getJSModule(java.lang.Class)' on a null object reference
                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3707)
                                                       at android.app.ActivityThread.access$2000(ActivityThread.java:229)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1903)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.react.bridge.JavaScriptModule com.facebook.react.bridge.ReactApplicationContext.getJSModule(java.lang.Class)' on a null object reference
                                                       at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:259)
                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3700)
                                                       at android.app.ActivityThread.access$2000(ActivityThread.java:229) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1903) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
```

3、如果加入了
```
public JPushReceiver() {
        HeadlessJsTaskService.acquireWakeLockNow(mModule.getReactApplicationContext());
}
```
，报错如下：

```
12-30 16:18:52.282 16330-16330/com.shefenqi.mall E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.shefenqi.mall, PID: 16330
                                                                   java.lang.RuntimeException: Unable to instantiate receiver cn.jpush.reactnativejpush.JPushModule$JPushReceiver: java.lang.NullPointerException
                                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2427)
                                                                       at android.app.ActivityThread.access$1700(ActivityThread.java:139)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5102)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                    Caused by: java.lang.NullPointerException
                                                                       at cn.jpush.reactnativejpush.JPushModule.access$800(JPushModule.java:30)
                                                                       at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.<init>(JPushModule.java:234)
                                                                       at java.lang.Class.newInstanceImpl(Native Method)
                                                                       at java.lang.Class.newInstance(Class.java:1208)
                                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2422)
                                                                       at android.app.ActivityThread.access$1700(ActivityThread.java:139) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5102) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                       at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by pampang** [comment]
@devhyunjae Right now I just wrap a try-catch in `JPushModule.java` to avoid the crash alert comes out.
Can't get a better idea yet

```
try {
                    Logger.d(TAG, "用户点击打开了通知");
                    WritableMap map = Arguments.fromBundle(bundle);
                    mRAC.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                            .emit("openNotification", map);
                    Intent intent = new Intent();
                    if (mModule != null && mModule.mContext != null) {
                        intent.setClass(context, mModule.mContext.getClass());
                        Logger.d(TAG, "context.getClass: " + mModule.mContext.getClass());
                        intent.putExtras(bundle);
                        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                        context.startActivity(intent);
                    } else {
                        String packageName = context.getApplicationContext().getPackageName();
                        Intent launchIntent = context.getPackageManager().getLaunchIntentForPackage(packageName);
                        launchIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_RESET_TASK_IF_NEEDED);
                        launchIntent.putExtras(bundle);
                        context.startActivity(launchIntent);
                    }
                }catch (Throwable e) {
                    // 如果报错，不进行任何操作
                    // 主要报错在：WritableMap map = Arguments.fromBundle(bundle); 这一句上
                    Log.i("Throwable", e.toString());
                }
```

**Comment by pampang** [comment]
@KenChoi1992 能否考虑一下我刚刚说的那个做法呢：在RN未初始化的时候，将推送的数据存到本地数据库中，等RN初始化完毕了，再取回来，这个会涉及到SDK的处理吗？

**Comment by devhyunjae** [comment]
@pampang looks like it is a better user experience than app crash.
@KenChoi1992 can you do that try-catch for next release?

**Comment by KenChoi1992** [comment]
@pampang 那样的话，Native 这边需要做的事情就复杂了，也不利于没有学过 Native 的同学，我们会考虑一个更全面的解决方案。

**Comment by pampang** [comment]
@KenChoi1992 roger that，期待新的版本！

**Comment by KenChoi1992** [comment]
@pampang 新版本增加了 try catch，至于后续的完整解决方案，我们还要讨论一下。

**Comment by pampang** [comment]
@KenChoi1992 在测试新版本的时候，发现这一行也会导致崩溃：
https://github.com/jpush/jpush-react-native/blob/master/android/src/main/java/cn/jpush/reactnativejpush/JPushModule.java#L249

设备：三星 GT-i9158P
系统：4.3
具体操作：
退出APP，并杀掉进程，再进行推送，就会出现”应用已停止“的弹框。

建议：在该if-else下也加一个try - catch。。。

![image](https://cloud.githubusercontent.com/assets/13509115/21671171/8bf249b4-d354-11e6-9f1a-8625539da393.png)


![image](https://cloud.githubusercontent.com/assets/13509115/21671010/85f99d24-d353-11e6-857f-27a3825973bd.png)

**Comment by pampang** [comment]
仔细浏览了一下上报崩溃的设备信息，发现：
1、android版本，从4.2 ~ 7.0均有报错，多数来自于JPushModule.java:248(也就是jpush-react-native1.1.31的249行)。
2、各大厂商（小米、魅族、华为......）均有躺枪，而且与定制rom的android版本无关。

如果需要更多信息，可以与我联系，能查到的一定提供~

**Comment by KenChoi1992** [comment]
@pampang 这就是应用被杀死后，从广播启动应用，因为 JS 没起来导致崩溃的情况吧，加 try－catch 并不是完美的解决方案

**Comment by pampang** [comment]
@KenChoi1992 我明白不是完美方案，但目前也只能如此啦...期待新版本！xDD

**Comment by devhyunjae** [comment]
@KenChoi1992 Hey um.. Can I get some news in here?

**Comment by KenChoi1992** [comment]
@devhyunjae We will discuss this problem later, to see if we should update jpush-android-sdk.

**Comment by KenChoi1992** [comment]
@pampang 有没有试过不用 WritableMap，而直接将收到的通知标题，内容，extra 等等直接转成 Json 字符串应该可以拿到？

**Comment by pampang** [comment]
刚刚在原有基础上直接尝试了一下，发现：

```
mRAC.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                            .emit("receiveNotification", json);
```

这个方法无法传递json欸，报错如下：

```
W/System.err: java.lang.RuntimeException: Cannot convert argument of type class org.json.JSONObject
W/System.err:     at com.facebook.react.bridge.Arguments.fromJavaArgs(Arguments.java:57)
W/System.err:     at com.facebook.react.bridge.JavaScriptModuleRegistry$JavaScriptModuleInvocationHandler.invoke(JavaScriptModuleRegistry.java:109)
W/System.err:     at $Proxy3.emit(Native Method)
W/System.err:     at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:261)
W/System.err:     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2446)
W/System.err:     at android.app.ActivityThread.access$1700(ActivityThread.java:139)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:136)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5102)
W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
W/System.err:     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by KenChoi1992** [comment]
@pampang 要改成 JSON 字符串，而不是将 JSON 对象传过去。。如果不行的话，我这边尝试在 Native 再写一个 service，继承 HeadlessJsTaskService，看看能否初始化 RN。

**Comment by pampang** [comment]
```
02-13 15:01:56.255 18738-18738/? I/JPushModule: 收到推送下来的通知: 测试
02-13 15:02:01.883 18738-18738/? D/JPushModule: 用户点击打开了通知
02-13 15:02:01.889 18738-18738/? W/System.err: java.lang.NullPointerException
02-13 15:02:01.890 18738-18738/? W/System.err:     at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:287)
02-13 15:02:01.892 18738-18738/? W/System.err:     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2446)
02-13 15:02:01.892 18738-18738/? W/System.err:     at android.app.ActivityThread.access$1700(ActivityThread.java:139)
02-13 15:02:01.893 18738-18738/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
02-13 15:02:01.893 18738-18738/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-13 15:02:01.893 18738-18738/? W/System.err:     at android.os.Looper.loop(Looper.java:136)
02-13 15:02:01.893 18738-18738/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5102)
02-13 15:02:01.893 18738-18738/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
02-13 15:02:01.893 18738-18738/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
02-13 15:02:01.894 18738-18738/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
02-13 15:02:01.894 18738-18738/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
02-13 15:02:01.894 18738-18738/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
```

估计是不行的，因为不仅仅是writeableMap尚未启动的问题，是整个react-native的环境都没有启动，所以还会有后续的问题。

By the way, 我这里看到的`(JPushModule.java:287)`为：
```
intent.setClass(context, mModule.mContext.getClass());
```

**Comment by KenChoi1992** [comment]
@pampang 感谢配合，稍后会将你加入到开发者贡献列表 ：）我现在正在尝试第二种方法了。

**Comment by KenChoi1992** [comment]
@pampang 现在的情况是即使用了 HeadlessJsTaskService, 并且在 MainApplication 中加了 
```
SoLoader.init();
```
在调用 RCTDeviceEventEmitter 下发事件的时候，仍然报 ReactApplicationContext 为空指针。

**Comment by KenChoi1992** [comment]
@devhyunjae @pampang Test HeadlessJsTaskService again, and the task was started, then threw an exception:
```
 java.lang.RuntimeException: Could not invoke HeadlessJsTaskSupport.notifyTaskFinished
                                                                  at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:332)
                                                                  at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
                                                                  at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                  at android.os.Handler.handleCallback(Handler.java:815)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                  at android.os.Looper.loop(Looper.java:207)
                                                                  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                  at java.lang.Thread.run(Thread.java:818)
                                                               Caused by: java.lang.reflect.InvocationTargetException
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
                                                                  at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158) 
                                                                  at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                  at android.os.Handler.handleCallback(Handler.java:815) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                  at android.os.Looper.loop(Looper.java:207) 
                                                                  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                                  at java.lang.Thread.run(Thread.java:818) 
                                                               Caused by: java.lang.AssertionError: Tried to finish non-existent task with id 1.
                                                                  at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:65)
                                                                  at com.facebook.react.jstasks.HeadlessJsTaskContext.finishTask(HeadlessJsTaskContext.java:111)
                                                                  at com.facebook.react.modules.core.HeadlessJsTaskSupportModule.notifyTaskFinished(HeadlessJsTaskSupportModule.java:40)
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318) 
                                                                  at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158) 
                                                                  at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                  at android.os.Handler.handleCallback(Handler.java:815) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                  at android.os.Looper.loop(Looper.java:207) 
                                                                  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                                  at java.lang.Thread.run(Thread.java:818) 
```
And here is the code to start HeadlessService:
```
...
// receive notification here
else if (JPushInterface.ACTION_NOTIFICATION_RECEIVED.equals(data.getAction())) {
                // 通知内容
                String alertContent = bundle.getString(JPushInterface.EXTRA_ALERT);
                // extra 字段的 json 字符串
                String extras = bundle.getString(JPushInterface.EXTRA_EXTRA);
                Logger.i(TAG, "收到推送下来的通知: " + alertContent);
                if (!isApplicationRunning(context)) {
                    Log.i(TAG, "应用尚未切换到前台运行过，启动 HeadlessService");
                    Intent intent = new Intent(context, HeadlessService.class);
                    intent.putExtra("data", bundle);
                    context.startService(intent);
                    HeadlessJsTaskService.acquireWakeLockNow(context);
                }
```
And I do remember call acquireWakeLockNow() before onReceive() has returned, seems after task finished, BaseJavaModule can't start up.

**Comment by pampang** [comment]
What if we store the push message, and handle it after the app is actually started-up? Is there any observer that can alert us when the start-up did finish?

**Comment by messense** [comment]
Same issue

**Comment by KenChoi1992** [comment]
@pampang One solution is that if received notifications when app hadn't been started up, tried to start up first, and caught exceptions if appeared, then saved the notifications, after user opened app, sent the notifications from native. JPush did provide [local notification API](https://docs.jiguang.cn/jpush/client/Android/android_api/#api_8),  do you guys agree with this solution ?

**Comment by pampang** [comment]
@KenChoi1992 in this case, remote notification will turn into a local notification? Personally, I think this solution can work and I agree with it.

**Comment by messense** [comment]
@KenChoi1992 I am ok with it.

**Comment by devhyunjae** [comment]
@KenChoi1992 I cannot fully understand what you said. You are saying that the user will receive an local notification? Even the JPush Process is not running?

**Comment by KenChoi1992** [comment]
@devhyunjae  Means that if jpush process start up application failed, the notifications will not show, when user open app, the notifications that previously received will show as local notifications.

**Comment by devhyunjae** [comment]
@KenChoi1992 got it

**Comment by KenChoi1992** [comment]
@devhyunjae @pampang @messense  Guys, we got a problem here:
![image](https://cloud.githubusercontent.com/assets/8196928/23389127/17d4f7e4-fda1-11e6-9d7e-185c9c7563cd.png)

When I try to start up application via HeadlessJsTaskService, then it will cause an runtime error, and the error I can't catch here：
![image](https://cloud.githubusercontent.com/assets/8196928/23389243/ddb46f4e-fda1-11e6-8203-66a0f23931c2.png)
Thus the code that saves notification as local notifications never execute.

**Comment by KenChoi1992** [comment]
I got an idea here, if we don't use HeadlessJsTaskService, we can avoid this error, all we need to do is judge the app is running or not(Foreground or background are OK), if true, work as usual. If not, we save the notification as local notification.

**Comment by KenChoi1992** [comment]
Guys, like I said before, v1.5.2 did this change, any problems welcome to point out, closing this issue now.
