### ISSUE TITLE
SDK以特定频率、超频次获取相关信息或者APP首次运行时，未到相关服务和场景提前收集相关信息， 读取已安装包名列表

### ISSUE THREAD

**Issue by Jeijie** [jpush/jpush-react-native#954]
## 你的运行环境

* 插件版本:    "jpush-react-native": "^3.1.0"
* react-native 版本：0.59.5
* jpush版本： jpush-android-5.4.0-google_play.jar

## 期望效果

隐私合规通过

## 实际效果

收到通信管理局整改通知，,隐私合规不通过，并且使用google版jar包替换，隐私合规监测还是不通过

### 隐私合规问题：

第三方SDK以特定频率、超频次获取相关信息或者APP首次运行时，未到相关服务和场景提前收集相关信息
 (SDK: 极光推送SDK) 读取已安装包名列表

## 重现步骤

1. 使用jpush-react-native 3.0.6版本集成隐私监测不通过
2. 使用jpush-react-native 3.0.6版本，并替换jpush 的jar包为google版本，集成隐私监测还不通过
3. 升级到jpush-react-native 3.1.0版本，并替换jpush的jar包jpush-android-5.4.0-google_play.jar版本，集成隐私监测还不通过

## Debug logs

包括 Android 或 iOS 的日志：
at android.app.ApplicationPackageManager.getInstalledPackagesAsUser()
	at android.app.ApplicationPackageManager.getInstalledPackages(ApplicationPackageManager.java:735)
	at java.lang.reflect.Method.invoke(Native Method)
	at cn.jiguang.common.m.d.c(Unknown Source:126)
	at cn.jiguang.common.m.d.b(Unknown Source:15)
	at cn.jiguang.common.m.d.b(Unknown Source:1)
	at cn.jiguang.common.m.d.a(Unknown Source:0)
	at cn.jiguang.common.m.d$1.b(Unknown Source:4)
	at cn.jiguang.am.d.a(Unknown Source:540)
	at cn.jiguang.am.d.b(Unknown Source:21)
	at cn.jiguang.common.m.d.a(Unknown Source:43)
	at cn.jiguang.ak.b.b(Unknown Source:50)
	at cn.jiguang.aa.b.f(Unknown Source:38)
	at cn.jiguang.aa.b.a(Unknown Source:0)
	at cn.jiguang.aa.b$b.a(Unknown Source:6)
	at cn.jiguang.aa.e.run(Unknown Source:9)

**Comment by itgyy** [comment]
我也刚遇到这个，你这边是怎么解决的？

**Comment by Jeijie** [comment]
升级到jpush-react-native 3.1.0版本，并替换jpush的jar包jpush-android-5.4.0-google_play.jar版本和jcore的jcore-android-4.7.0-google_play.jar可以了 @itgyy

**Comment by Chocolate-Lee** [comment]
你好，我这边升级版本后，报错jpush和jcore都显示undefined.JPushPackage
